# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: open-cluster-management

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: acm-custom-registry
    newName: quay.io/acm-d/acm-custom-registry
    newTag: 1.0.0-2020-05-07-19-51-26

# list of Resource Config to be Applied
resources:
  - deployment.yaml
  - service.yaml
  - catalog-source.yaml
  - operator-group.yaml
  - subscription.yaml
